#!/usr/bin/env bash
set -e

BUILD_DIR="./build"

if [ ! -d "$BUILD_DIR" ]; then
    cmake --preset=default
fi

if [ -z "$1" ]; then
    echo "Usage: $0 <target>"
    echo "Usage: $0 test <target>"
    exit 1
fi

TARGET="$1"

if [ "$TARGET" = "cmake" ]; then
    cmake --preset=default
    exit $?;
fi

if [ "$TARGET" = "all" ]; then
  ninja -C "$BUILD_DIR"
  exit $?;
fi

if [ "$TARGET" = "tests" ]; then 
  ninja -C "$BUILD_DIR"
  ninja -C "$BUILD_DIR" test
  exit $?;
fi

if [ "$TARGET" = "bench" ]; then 
  if [ -z "$2" ]; then
    echo "Usage: $0 bench <target>"
    exit 1
  fi
  TARGET="${2}_bench"
  TARGET=$(echo "$TARGET" | tr '[:upper:]' '[:lower:]')
fi

if [ "$TARGET" = "test" ]; then
  if [ -z "$2" ]; then
    echo "Usage: $0 test <target>"
    exit 1
  fi
  TARGET="${2}_test"
  TARGET=$(echo "$TARGET" | tr '[:upper:]' '[:lower:]')
fi

if [ "$TARGET" = "profile" ]; then 
  ninja -C "$BUILD_DIR" "$2" && echo "Compilation success"
  EXEC="$BUILD_DIR/bin/$2"
  if [ -x "$EXEC" ]; then
    DYLD_INSERT_LIBRARIES="/opt/homebrew/lib/libtcmalloc.dylib:/opt/homebrew/lib/libprofiler.dylib" \
    DYLD_FORCE_FLAT_NAMESPACE=1 \
    CPUPROFILE="$2.prof" \
    "$EXEC"
  else
    echo "Executable not found: $EXEC"
    exit 1
  fi

  echo -e "then run 'pprof $EXEC $2.prof'"

  exit 0
fi

ninja -C "$BUILD_DIR" "$TARGET" && echo "Compilation success"

# Run executable if it exists
EXEC="$BUILD_DIR/bin/$TARGET"
if [ -x "$EXEC" ]; then
  "$EXEC"
else
  echo "Executable not found: $EXEC"
  exit 1
fi
